language: ruby
services:
  - redis
rvm:
  - jruby-19mode
  - rbx-19mode
  - 1.9.3
  - 2.0.0
  - 2.1.0
  - 2.1.1
env:
  matrix:
    - SIDEKIQ_VERSION="~> 2.6.0"
    - SIDEKIQ_VERSION="~> 2.17.0"
    - SIDEKIQ_VERSION="~> 3.0.0"
matrix:
  allow_failures:
    - rvm: jruby-19mode
    - rvm: rbx-19mode
branches:
  only:
    - master
notifications:
  email:
    recipients:
      - pablo@pablocantero.com
