language: ruby
rvm:
  - 1.9.3
  - jruby-19mode
  - rbx-19mode
  - 2.0.0
  - 2.1.0
  - 2.1.1
env:
  matrix:
    - SIDEKIQ_VERSION="~> 2.5.0"
    - SIDEKIQ_VERSION="~> 2.17.0"
    - SIDEKIQ_VERSION="~> 3.0.0"
branches:
  only:
    - master
notifications:
  email:
    recipients:
      - pablo@pablocantero.com
matrix:
  allow_failures:
    - rvm: jruby-19mode
    - rvm: rbx-19mode
